const songs = [
  {
    id: 1,
    name: 'Holding me back',
    artist: 'Shawn mendes',
    artistImg: '/images/shawn.webp',
    song: '/songs/back.mp3',
    image: 'https://i.scdn.co/image/ab67616d00001e021376b4b16f4bfcba02dc571b',
    Genre: 'Pop rock / Dance-pop',
    Release: 'April 20, 2017',
    Album: 'Illuminate (Deluxe)',
    Type: 'Single',
    Sound: 'Electric guitar driven pop rock with upbeat rhythm and energetic vocals',
    Theme: 'Freedom in romance, letting go of inhibitions, adventurous love',
    Inspiration: 'Inspired by a fictional girl from a movie script Mendes read, not a real person',
    bg: 'lightblue',
    bgCol: '#1d3c66'
  },
  {
    id: 7,
    name: 'Lose My Mind',
    artist: 'Don Toliver feat. Doja Cat',
    artistImg: '/images/lose.jpg',
    song: '/songs/lose.mp3',
    image: 'https://i.scdn.co/image/ab67616d0000b273bed9c7b9e33025a81d4d02e4',
    Genre: 'Pop rap / Electropop',
    Release: 'April 30, 2025',
    Album: 'F1 The Album',
    type: 'Single',
    Sound: 'High-energy electronic production with synth-heavy beats, a futurist, racing-inspired vibe; smooth rap vocals by Don Toliver give way to Doja Cat’s sharper, expressive verse — blending atmospheric verses with an intense, cinematic chorus.',
    Theme: 'Adrenaline, tension, letting go — capturing the rush and emotional volatility of high-stakes racing and desire. The lyrics and mood reflect a sense of losing control, inner conflict, and the chaos that comes with chasing speed and passion.',
    Inspiration: 'Created for the soundtrack of F1 The Movie, to match the film’s high-octane racing sequences and emotional arcs. The track aims to combine cinematic intensity (influenced by film soundtrack sensibilities) with mainstream pop/rap sensibilities, giving a modern energetic anthem for the movie.',
    bg: 'neon',
    bgCol: '#0f1013'
  }

  ,
  {
    id: 2,
    name: 'Feel it',
    artist: 'd4vd',
    artistImg: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:AN…Y4OHx_rqCi2TnChW7d683dPxEpo-l2YUZSeUE4v0w7Iw&s=10',
    song: '/songs/feel-it.mp3',
    image: '/images/feel.jpg',
    Genre: 'Funk and disco-pop',
    Release: 'March 28, 2024',
    Album: 'WITHERED (as a bonus track)',
    type: 'Album',
    Sound: 'Features a heavy bass line and groovy, upbeat guitar riffs',
    Theme: 'The lyrics express a deep certainty in a romantic partner and a desire not to lose them',
    Inspiration: 'The song was written for the soundtrack of the Amazon Prime Video series Invincible, with d4vd explaining that the animated visuals inspired the playful, "cat and mouse" vibe of the song',
    bg: 'lightblue',
    bgCol: 'red'
  },
  {
    id: 3,
    name: 'End of beginning',
    artist: 'Djo',
    artistImg: '/images/end.jpg',
    song: '/songs/endofbeginning.mp3',
    image: '/images/end.jpg',
    Genre: 'Indie pop / synth-pop',
    Release: 'September 16, 2022 (album), later as single March 1, 2024',
    Album: 'DECIDE',
    type: 'Album',
    Sound: 'Dreamy synth layers, nostalgic guitar tones and driving rhythm',
    Theme: 'Reflecting on past versions of oneself and moving forward (“wave goodbye to the end of beginning”)',
    Inspiration: 'Written by Joe Keery under his moniker Djo, the song’s resurgence came via TikTok and explores nostalgia and change',
    bg: 'red',
    bgCol: 'blue'
  },
  {
    id: 4,
    name: 'The rare occations',
    artist: 'Notion',
    artistImg: '/images/notion1.jpg',
    song: '/songs/rare.mp3',
    image: '/images/notion.jpg',
    Genre: 'Indie Rock / Alternative',
    Release: '2016',
    Album: 'Futureproof',
    type: 'Album',
    Sound: 'Energetic indie rock with explosive vocals and punchy instrumentation',
    Theme: 'Self-reflection, doubt, emotional tension',
    Inspiration: 'Explores inner struggles and the feeling of losing control',
    bg: 'purple',
    bgCol: 'red'
  },
  {
    id: 5,
    name: "I ain't worried",
    artist: 'OneRepublic',
    artistImg: '/images/worry.jpeg',
    song: '/songs/worry.mp3',
    image: '/images/worry.jpeg',
    Genre: 'Pop rock / Mainstream pop',
    Release: 'May 13, 2022',
    Album: 'Top Gun: Maverick – Music from the Motion Picture',
    type: 'Single',
    Sound: 'Bright, breezy production with catchy whistled hook and upbeat tempo',
    Theme: 'Carefree living, embracing the moment, letting go of worries',
    Inspiration: 'Written for the film Top Gun: Maverick and tailored to the film’s beach football scene',
    bg: 'green',
    bgCol: '#50C878'
  },
  {
    id: 6,
    name: 'Golden hour',
    artist: 'jvke',
    artistImg: '/images/jvke.jpg',
    song: '/songs/golden.mp3',
    image: '/images/golden.jpeg',
    Genre: 'Pop / Electronic pop',
    Release: 'Unknown',
    Album: 'Unknown',
    type: 'Single',
    Sound: 'Soothing vocals over a mellow beat with emotional resonance',
    Theme: 'Romantic or reflective mood set at a golden hour moment',
    Inspiration: 'Captures that perfect “golden hour” time in life when everything feels right',
    bg: 'white',
    bgCol: 'yellow'
  },
  {
    id: 7,
    name: 'Moonlight',
    artist: 'Dhruv',
    artistImg: '/images/dhruv.webp',
    song: '/songs/moonlight.mp3',
    image: '/images/moonlight.jpg',
    Genre: 'Indie pop / R&B',
    Release: 'Unknown',
    Album: 'Unknown',
    type: 'Single',
    Sound: 'Smooth vocals with ambient instrumentation and intimate feel',
    Theme: 'Quiet moments, introspection under the moonlight',
    Inspiration: 'Inspired by late-night reflections and soft mood settings',
    bg: 'orange',
    bgCol: 'white'
  },
  {
    id: 8,
    name: 'Tadow',
    artist: 'Masego',
    artistImg: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:AN…3ZK3qc6V7wsxadxD6FTxR4CZ-ts3UaWrNGG1HAEHyz8EP0A&s',
    song: '/songs/tadow.mp3',
    image: '/images/tadow.jpg',
    Genre: 'Jazz / R&B / Future funk',
    Release: 'March 10, 2017',
    Album: 'Last Summer',
    type: 'Album',
    Sound: 'Live sax riffs, groovy rhythm, smooth vocals – a fusion cut',
    Theme: 'Romantic and playful with strong groove',
    Inspiration: 'Masego’s signature “traphouse jazz” sound combining sax, hip-hop and funk elements',
    bg: 'blue',
    bgCol: 'gray'
  },
  {
    id: 9,
    name: 'Changes',
    artist: 'Charlie Puth',
    artistImg: '/images/changes.jpeg',
    song: '/songs/changes.mp3',
    image: '/images/changes.jpeg',
    Genre: 'Pop',
    Release: 'February 13, 2018',
    Album: 'Voicenotes',
    type: 'Album',
    Sound: 'Piano-driven ballad with emotional lyrics and pop hooks',
    Theme: 'Struggles of self-renewal and transformation in a relationship',
    Inspiration: 'Charlie Puth wrote it after experiencing major life and creative transitions',
    bg: 'aqua',
    bgCol: '#7DF9FF'
  },
  {
    id: 10,
    name: 'Blinding lights',
    artist: 'The Weeknd',
    artistImg: '/images/blinding.jpeg',
    song: '/songs/lights.mp3',
    image: '/images/blinding.jpeg',
    Genre: 'Synth-pop / 80s-influenced pop',
    Release: 'November 29, 2019',
    Album: 'After Hours',
    type: 'Album',
    Sound: 'Up-tempo 80s synths, driving beat and nostalgic vibe',
    Theme: 'Escapism, night-life, longing and energy in the darkness',
    Inspiration: 'Inspired by 80s pop and film soundtrack aesthetics, reflecting The Weeknd’s darker studio persona',
    bgCol: 'red'
  },
  {
    id: 11,
    name: 'Call this love',
    artist: 'Matthew Ifield',
    artistImg: '/images/matthew.jpg',
    song: '/songs/thislove.mp3',
    image: '/images/thislove.jpg',
    Genre: 'Indie pop / Folk pop',
    Release: 'Unknown',
    Album: 'Unknown',
    type: 'Single',
    Sound: 'Warm acoustic instrumentation, gentle vocals and a soothing melody',
    Theme: 'Affection, connection and the simple joys of loving someone',
    Inspiration: 'Captures the feeling of calling something love and appreciating that moment',
    bgCol: 'red'
  },
  {
    id: 12,
    name: 'Noor',
    artist: 'MBL_ & Ayarkay.',
    artistImg: '/images/noor.jpg',
    song: '/songs/noor.mp3',
    image: '/images/noor.jpg',
    Genre: 'Regional Indian / Malayalam Pop',
    Release: 'August 1, 2025',
    Album: 'Single',
    type: 'Single',
    Sound: 'Modern production with soulful vocals and poetic storytelling',
    Theme: 'Emotional depth, reflection and lyrical serenity',
    Inspiration: 'A collaboration between MBL_ and Ayarkay blending traditional and contemporary musical influences',
    bg: 'blueviolet',
    bgCol: 'yellow'
  }
];

export default songs;
